package com.zhifaios.eyes.touch;

public enum AispectTouchErrorCode {
    MODEL_UNAVAILABLE,
    MODEL_SCHEMA_MISMATCH,
    MODEL_LOAD_FAILED,
    SENSOR_UNAVAILABLE,
    TOUCH_SEQUENCE_INVALID,
    REMOTE_MODEL_REJECTED,
    RECORD_SAVE_FAILED,
    INFERENCE_FAILED,
    UNKNOWN
}
